if(EXISTS "/home/ndomboukamdem/Documents/INFL/Master_2/Code2/build_bench/test/test_CNN[1]_tests.cmake")
  include("/home/ndomboukamdem/Documents/INFL/Master_2/Code2/build_bench/test/test_CNN[1]_tests.cmake")
else()
  add_test(test_CNN_NOT_BUILT test_CNN_NOT_BUILT)
endif()
