if(EXISTS "/home/ndomboukamdem/Documents/INFL/Master_2/Code2/build_bench/test/test_DropoutLayer[1]_tests.cmake")
  include("/home/ndomboukamdem/Documents/INFL/Master_2/Code2/build_bench/test/test_DropoutLayer[1]_tests.cmake")
else()
  add_test(test_DropoutLayer_NOT_BUILT test_DropoutLayer_NOT_BUILT)
endif()
