if(EXISTS "/home/ndomboukamdem/Documents/INFL/Master_2/Code2/build_bench/test/test_Dimensions[1]_tests.cmake")
  include("/home/ndomboukamdem/Documents/INFL/Master_2/Code2/build_bench/test/test_Dimensions[1]_tests.cmake")
else()
  add_test(test_Dimensions_NOT_BUILT test_Dimensions_NOT_BUILT)
endif()
