#pragma once
#include "CNN.hpp"
#include "ConvLayer.hpp"
#include "ConvLayerDataParallel.hpp"
#include "ConvLayer3D.hpp"
#include "ActivationLayer.hpp"
#include "PoolLayer.hpp"
#include "DenseLayer.hpp"
#include "LossLayer.hpp"
#include "Optimizer.hpp"
#include "Dimensions.hpp"
#include "DropoutLayer.hpp"
#include "DataLoader.hpp"
#include "DataLoader3D.hpp"
#include "MedMNIST3DDataset.hpp"
#include "SparseTensor.hpp"
#include "SparseConvLayer3D.hpp"
#include "SparseConvAdapterLayer.hpp"
#include "WindowAttention3DLayer.hpp"    // ← nouveau
#include "Augmentation3D.hpp"
#include "BatchNorm3DLayer.hpp"
#include "ConvLayerDataParallel.hpp"
#include "DenseLayerDataParallel.hpp"
#include "DenseLayerDataParallel.hpp"
#include "DenseLayerModelParallel.hpp"

// ConvNeXt Dense Components
#include "LayerNorm3DLayer.hpp"
#include "DepthwiseConvLayer3D.hpp"
#include "PatchifyStem3D.hpp"
#include "DenseDownsample3D.hpp"
#include "ConvNeXtBlock3D.hpp"

// ConvNeXt Sparse Components
#include "LayerNorm3DSparse.hpp"
#include "PatchifyStem3DSparse.hpp"
#include "SparseDownsample3D.hpp"
#include "ConvNeXtBlock3DSparse.hpp"
